# **Numpy tutorial by Aditya**

we will learn creating arrays , using random function , indexing arrays , slicing arrays , statistical and mathematical functions and practical working.

We will do some operations on real world datasets which we will import from kaggle.

In [ ]:
import numpy as np # np is the alias

In [ ]:
arr = np.array([1,2,3,4,5]) # 1 dimensional or 1-D array
print(arr)
print(type(arr)) # checking the type of the variable
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [ ]:
arr2d = np.array([[1,2,3],[4,5,6]]) # 2-D array
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]) # 3-D array
print(arr2d)
print(type(arr2d))
print(arr3d)
print(type(arr3d))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [ ]:
print(np.shape(arr)) # getting shapes ---> rows x columns
print(np.shape(arr2d)) # shape of 2-D array
print(np.shape(arr3d))

(5,)
(2, 3)
(2, 3, 3)


In [ ]:
arrn = np.reshape(arr,(5,1)) # know this that even shape of arra was shown as (5,) but actually it was in the format of
# (1,5) which means a single row and 5 columns and here we reversed the order of the matrix
print(arrn)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
arrn2d = np.reshape(arr3d,(9,-1)) # we converted this 3-D arr3d array into a new 2-D array. you can skip one of the shape values as -1 and reshape will calculate the value of that place automatically.
# but you can't leave more than one shape value as -1
print(arrn2d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
mat = np.random.rand(3,3,3) # this is use of random function where we generate random inputs of elements for a predefined shape of array.
# THe elements always range from 0 to 1 both being exclusive.
print(mat)

[[[0.99434016 0.36229559 0.05880997]
  [0.00119357 0.78762347 0.27577327]
  [0.31172293 0.57588618 0.82029191]]

 [[0.41808645 0.32899422 0.07117116]
  [0.41670933 0.60796364 0.08776997]
  [0.42849928 0.30072741 0.65201611]]

 [[0.80376581 0.65418278 0.82665583]
  [0.98779088 0.54069311 0.82770248]
  [0.25467166 0.93240155 0.21479891]]]


In [ ]:
mat1 = np.random.rand(3,3,3) # as u can see we ran the same piece of code with new name and the elements are different
# if you run this or previous block , the array will change again
print(mat)

[[[0.99434016 0.36229559 0.05880997]
  [0.00119357 0.78762347 0.27577327]
  [0.31172293 0.57588618 0.82029191]]

 [[0.41808645 0.32899422 0.07117116]
  [0.41670933 0.60796364 0.08776997]
  [0.42849928 0.30072741 0.65201611]]

 [[0.80376581 0.65418278 0.82665583]
  [0.98779088 0.54069311 0.82770248]
  [0.25467166 0.93240155 0.21479891]]]


In [ ]:
state = np.random.RandomState(21) # here we state a random state , which means we are storing this session and when we use
# this random state again , you will get the same array as this one.
# The number 21 can be replaced with any number as per your wish , but when u want to get the same sample you need to set
# the same number again
mat2 = np.random.rand(3,3,3)
print(mat)

[[[0.99434016 0.36229559 0.05880997]
  [0.00119357 0.78762347 0.27577327]
  [0.31172293 0.57588618 0.82029191]]

 [[0.41808645 0.32899422 0.07117116]
  [0.41670933 0.60796364 0.08776997]
  [0.42849928 0.30072741 0.65201611]]

 [[0.80376581 0.65418278 0.82665583]
  [0.98779088 0.54069311 0.82770248]
  [0.25467166 0.93240155 0.21479891]]]


In [ ]:
state = np.random.RandomState(21) # this code is proof of the previous claim
mat3 = np.random.rand(3,3,3)
print(mat)

[[[0.99434016 0.36229559 0.05880997]
  [0.00119357 0.78762347 0.27577327]
  [0.31172293 0.57588618 0.82029191]]

 [[0.41808645 0.32899422 0.07117116]
  [0.41670933 0.60796364 0.08776997]
  [0.42849928 0.30072741 0.65201611]]

 [[0.80376581 0.65418278 0.82665583]
  [0.98779088 0.54069311 0.82770248]
  [0.25467166 0.93240155 0.21479891]]]


# Create an array of zeros of given shape

np.zeros(): create array of all zeros in given shape

np.zeros_like(): create array of all zeros with the same shape and data type as the given input array



In [ ]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64) # we are initially telling that elements inside this array should be
# of complex data type
zeros = np.zeros_like(arr)
print(zeros)
print(type(zeros.dtype))
print('Data Type: ' + str(zeros.dtype)) # we used type casting here

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
<class 'numpy.dtype[complex64]'>
Data Type: complex64


Simillarlly you can use np.ones and np.empty to create srrays of ones and empty array respectively.

# arange function

this function will help us to directly generate a 1-D array with elements in a specified range

In [ ]:
A = np.arange(1,10) # 1 will inclusive and 10 will exclusive
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create an identity matrix of given size
np.eye(size, k=0): create an identity matrix of given size

*  size: the size of the identity matrix
*  k: the diagonal offset

np.identity(): same as np.eye() but does not carry parameters

In [ ]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


# Stacking of arrays

Stacking means concatinating the elements of two arrays of compatible size , vertically or horizontally

In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.hstack((a1, a2)) # Horizontal Stacking of Numpy Arrays

print(o)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

o = np.vstack((a1, a2)) # Vertically Stacking of Numpy Arrays

print(o)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


# Mathematics in numpy

you can perfom basic operations on the arrays like addition of a number to all the elements , multiplying a constant to all the elements , giving array as argument to functions like , sin() , cos() , sqrt() , log()

In [ ]:
arr = np.random.rand(5,5)
arr

array([[0.42752229, 0.97560515, 0.64819273, 0.35896982, 0.81815627],
       [0.7504197 , 0.85656032, 0.93833411, 0.33154959, 0.21227733],
       [0.51700061, 0.96929442, 0.68195855, 0.4898989 , 0.49549877],
       [0.90767456, 0.02340654, 0.00704502, 0.39748554, 0.88047492],
       [0.43754685, 0.81566137, 0.90993406, 0.83206697, 0.96090659]])

In [ ]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.42752229 10.97560515 10.64819273 10.35896982 10.81815627]
 [10.7504197  10.85656032 10.93833411 10.33154959 10.21227733]
 [10.51700061 10.96929442 10.68195855 10.4898989  10.49549877]
 [10.90767456 10.02340654 10.00704502 10.39748554 10.88047492]
 [10.43754685 10.81566137 10.90993406 10.83206697 10.96090659]]
[[-9.57247771 -9.02439485 -9.35180727 -9.64103018 -9.18184373]
 [-9.2495803  -9.14343968 -9.06166589 -9.66845041 -9.78772267]
 [-9.48299939 -9.03070558 -9.31804145 -9.5101011  -9.50450123]
 [-9.09232544 -9.97659346 -9.99295498 -9.60251446 -9.11952508]
 [-9.56245315 -9.18433863 -9.09006594 -9.16793303 -9.03909341]]
[[4.27522288 9.75605152 6.48192733 3.58969824 8.18156266]
 [7.50419696 8.56560318 9.38334111 3.31549595 2.12277326]
 [5.17000612 9.69294422 6.81958547 4.89898903 4.95498768]
 [9.07674561 0.23406544 0.07045017 3.97485537 8.80474918]
 [4.37546851 8.15661367 9.09934058 8.32066967 9.6090659 ]]
[[0.04275223 0.09756052 0.06481927 0.03589698 0.08181563]
 [0.07504197 0.0856

In [ ]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


In [ ]:
print(np.exp(arr)) # exponetial function of arr
# natural log
print(np.log(arr))
print()
# base 2
print(np.log2(arr))
print()
# base 10
print(np.log10(arr))
print()
# elementwise sin(arr)
print(np.sin(arr))
print()
# elementwise square root
print(np.sqrt(arr))

[[1.53345336 2.65277206 1.91208206 1.43185359 2.2663175 ]
 [2.1178887  2.35504614 2.55572032 1.39312524 1.23649075]
 [1.67699015 2.63608384 1.97774745 1.63215121 1.64131667]
 [2.47855211 1.02368263 1.00706989 1.48807827 2.41204496]
 [1.54890287 2.26067031 2.48415872 2.29806386 2.61406528]]
[[-0.84974886 -0.02469733 -0.4335672  -1.02451695 -0.20070193]
 [-0.28712263 -0.15483054 -0.0636492  -1.10397787 -1.54986172]
 [-0.65971122 -0.03118687 -0.3827864  -0.71355623 -0.70219041]
 [-0.09686938 -3.75473963 -4.95543467 -0.92259673 -0.12729384]
 [-0.82657149 -0.203756   -0.09438315 -0.18384235 -0.03987808]]

[[-1.22592846 -0.03563072 -0.62550525 -1.47806552 -0.28955167]
 [-0.4142304  -0.22337325 -0.09182638 -1.5927034  -2.23597782]
 [-0.95176211 -0.04499315 -0.55224405 -1.02944403 -1.01304662]
 [-0.13975297 -5.41694424 -7.14918103 -1.33102573 -0.18364619]
 [-1.19249059 -0.29395777 -0.1361661  -0.26522845 -0.0575319 ]]

[[-0.36904124 -0.01072591 -0.18829584 -0.44494206 -0.08716374]
 [-0.1246957

## Matrix as a `NumPy` array

Everything in `NumPy` is an array. A matrix is also an array. Let us create a simple matrix:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Adding two matrices

Let us now add the following matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} + \textbf{B}  = \begin{bmatrix}
6 & 8\\
10 & 12
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A+B)

[[ 6  8]
 [10 12]]


## Scaling a matrix

Scaling a matrix is nothing but element-wise multiplication:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

then,

$$
3 \textbf{M} = \begin{bmatrix}
3 & 6 & 9\\
12 & 15 & 18\\
21 & 24 & 27
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.arange(1,10).reshape(3,3)
print(3*A)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


## Element-wise multiplication of matrices

Consider two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

The element-wise product is given by $\textbf{A} \odot \textbf{B}$:

$$
\textbf{C} = \textbf{A} \odot \textbf{B} = \begin{bmatrix}
5 & 12\\
21 & 32
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A*B)

[[ 5 12]
 [21 32]]


### Example-2

We might want to square each element of the matrix. If $\textbf{A}$ is a matrix, then $\textbf{B}$ could be defined element-wise as follows:

$$
B_{ij} = A_{ij}^2
$$

Let us compute $\mathbf{B}$ for the following matrix:

$$
\mathbf{A} = \begin{bmatrix}
1 & \sqrt{2}\\
\sqrt{3} & 2
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([[1 , np.sqrt(2)],[np.sqrt(3),2]]) # np.sqrt() is a mathematical tool for square root of a number
B = A**2
print(B) # using np.sqrt() will convert the values inside the matrix into float type by default.

[[1. 2.]
 [3. 4.]]


## Transpose of a matrix

Given a matrix $\textbf{M}$:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

then, its transpose $\textbf{M}^{T}$ is:

$$
\textbf{M}^{T} = \begin{bmatrix}
1 & 4\\
2 & 5\\
3 & 6
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.array([[1,2,3],[4,5,6]])
y = np.transpose(M)
y

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
y = M.T # better option than np.transpose
y

array([[1, 4],
       [2, 5],
       [3, 6]])

## Products involving matrices and vectors

We will look at the following products:
- matrix - matrix
- matrix - vector
- vector - matrix
- vector - vector

### Product of two matrices

Given two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
6 & 7\\
8 & 9\\
10 & 11
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} \times \textbf{B} = \begin{bmatrix}
52 & 58\\
124 & 139
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
A @ B

array([[ 58,  64],
       [139, 154]])

### Product of a matrix and a (column) vector

Given the matrix $\mathbf{A}$ and the vector $\mathbf{x}$:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}, \mathbf{x} = \begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
$$

The product $\mathbf{Ax}$ is given by:

$$
\mathbf{C} = \mathbf{A x} = \begin{bmatrix}
44\\
107\\
170
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = np.array([6,7,8])
A @ X # here even if you don't give the transposed matrix , it will automatically do the transpose and give you the ccorrect output.

array([ 44, 107, 170])

### (Inner) Product of a (row) vector and a (column) vector

The product of a row vector and a column vector is nothing but the usual dot product:

$$
\mathbf{x}^T = \begin{bmatrix}
1 & 2 & 3
\end{bmatrix}, \quad
\mathbf{y} = \begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
$$

The product $\mathbf{x}^T \mathbf{y}$ is then:

$$
\mathbf{x}^T \mathbf{y} = 32
$$

In `NumPy`:

In [ ]:
# you can again use @ here , it will give you the required answer

## Indexing and Slicing

Just like lists in Python, `NumPy` arrays can be indexed and sliced. Slicing is useful if we want to work with a portion of an array. We will look at some examples.

### Example-1: Row-slice

We will extract the third row of the matrix $\mathbf{M}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8\\
9 & 10
\end{bmatrix}
$$



In `NumPy`:

In [ ]:
V = np.arange(1,11) # it can't shape a 1-D array of prime number of elements to any new shape.
V = V.reshape(5,2) # will make our life simpler by converting an array to required shape.
# if you set any one parameter to -1 in reshape() funtion will automatically compute the valid value of that particular parameter.
V

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
print(V[2]) #for rows you can just simply apply the logic of list indexing method to get your answer.

[5 6]


### Example-2: Column slice

Let us now extract the second column of the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
V = np.arange(1,10).reshape(3,3) # you can attach two functions to make your code shorter.
V

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(V[1,2]) # this simply means traversing to 2nd row and 3rd column
print(V[:,1]) # adding a colon means getting all the elements related to that parameter.

6
[2 5 8]


### Example-3: Submatrix slice

Now, we want to extract the $2 \times 2$ submatrix colored in blue from $M$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & \color{blue}7 & \color{blue}8\\
9 & 10 & \color{blue}{11} & \color{blue}{12}\\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
V = np.arange(1,17).reshape(4,4)
V

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# In line 22 , we just used 1 number for input in row and column , but we can give a series
# of rows and columns as input which will enable us to use submatrix slice

V[1:3 , 2:4] #here we used '1:3' to specify that we wan't 2nd to 3rd row. we used '2:4' to
# specify that we want from column 3 to 4 . And hence u can see the result.

array([[ 7,  8],
       [11, 12]])

## Matrix algebra

There are several important matrix operations that we will list down here. The `np.linalg` module helps us perform these operations effortlessly.

## Rank, Inverse

We can get the rank of a matrix and its inverse as follows:

In [ ]:
V[1,2]=22  # changed an element in previous matrix , as that was a singular matrix , whose inverse is not possible.

# rank

print(np.linalg.matrix_rank(V))

# inverse

print(np.linalg.inv(V))

3
[[ 3.75299969e+14 -6.66666667e-02 -1.12589991e+15  7.50599938e+14]
 [-5.62949953e+14  6.66666667e-02  1.68884986e+15 -1.12589991e+15]
 [-5.55555556e-02  6.66666667e-02  3.33333333e-02 -4.44444444e-02]
 [ 1.87649984e+14 -6.66666667e-02 -5.62949953e+14  3.75299969e+14]]


### Pseuodoinverse

The pseudoinverse $\mathbf{M}^{\dagger}$ of a matrix $\mathbf{M}$ with real entries satisfies the following properties:

- $\mathbf{M} \mathbf{M}^{\dagger} \mathbf{M} = \mathbf{M}$
- $\mathbf{M}^{\dagger} \mathbf{M} \mathbf{M} = \mathbf{M}^{\dagger}$
- $\mathbf{M} \mathbf{M}^{\dagger}$ is symmetric
- $\mathbf{M}^{\dagger} \mathbf{M}$ is symmetric

Let us go ahead and verify this for the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
3 & 6 & 9
\end{bmatrix}
$$

Note: For a complete list of properties of the pseudoinverse, check out this [link](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse#Definition).

In [ ]:
M = np.array([[1,2,3],[3,6,9]])
print(np.linalg.matrix_rank(M))
print(np.linalg.pinv(M)) # pseudo-inverse

1
[[0.00714286 0.02142857]
 [0.01428571 0.04285714]
 [0.02142857 0.06428571]]


## Eigenvalues and Eigenvectors

Given a symmetric matrix $\mathbf{M}$ let us find its eigenvalues and eigenvectors:

$$
\mathbf{M} = \begin{bmatrix}
1 & 0 & -3\\
0 & 5 & 2\\
-3 & 2 & 8
\end{bmatrix}
$$

In [ ]:
M = np.array([[1,0,-3],[0,5,2],[-3,2,8]])

eigen_values , eigen_vector = np.linalg.eigh(M) # linal.eigh() returns two values , the 1st one is eigne values and 2nd is corresponding eigen vectors.

print(eigen_values , eigen_vector)

[-0.20942046  4.36588492  9.84353554] [[ 0.91805853  0.26010485 -0.2991889 ]
 [-0.14209114  0.92042494  0.36418131]
 [ 0.37010626 -0.29182767  0.88196257]]
